### ISSUE TITLE
"Listing directory failed" on time-style ls option

### ISSUE THREAD

**Issue by gaydenko** [escherdragon/sunrise-commander#32] opened 2015-06-08 10:39 UTC
Hi!
I have tried to add time style option to ls options list:
```
'(sr-listing-switches "--dired --group-directories-first -alh --time-style=\"+%y-%m-%d %H:%M:%S\"")
```
But have got 
```
Listing directory failed but `access-file' worked
```
error message, while both sr buffers were filled with current buffer content. The option does work from command line. Have I missed something (I'm very new with emacs)?

Arch Linux is in use.

**Comment by escherdragon** [comment] 2015-06-09 13:59
Hello Andrew,

I haven't really had the time to find the root cause of your problem, but I
can offer you a simple workaround for the time being: instead of using a
regular space which needs to be escaped using quotation marks, use any of
the unicode space characters
<https://www.cs.tut.fi/~jkorpela/chars/spaces.html>, e.g. EN QUAD (U+2000)
in your time-style pattern. It's very easy to do it in emacs: press C-x
8-RET and then write #x2000 at the prompt in the minibuffer.

I'll let you know when I find what is actually causing the problem with the
quotation marks.

Cheers,

On Mon, Jun 8, 2015 at 12:39 PM, Andrew Gaydenko <notifications@github.com>
wrote:

> Hi!
> I have tried to add time style option to ls options list:
>
> '(sr-listing-switches "--dired --group-directories-first -alh --time-style=\"+%y-%m-%d %H:%M:%S\"")
>
> But have got
>
> Listing directory failed but `access-file' worked
>
> error message, while both sr buffers were filled with current buffer
> content. The option does work from command line. Have I missed something (I
> very new with emacs)?
>
> Arch Linux is in use.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/escherdragon/sunrise-commander/issues/32>.
>



-- 
José A. Romero L.
escherdragon@gmail.com
"We who cut mere stones must always be envisioning cathedrals."
(Quarry worker's creed)

**Comment by gaydenko** [comment] 2015-06-09 14:29
Jose, thanks! - the workaround does work.

**Comment by escherdragon** [comment] 2015-06-13 19:41
OK, I've just made a short investigation and it turned out to be a bug upstream, in dired (see: http://debbugs.gnu.org/cgi/bugreport.cgi?bug=18875). I don't think there's any sense in even trying to fix this in SC, so I'm closing the issue -- as soon as this gets fixed in dired, it'll be fixed in SC too.

**Closed by escherdragon** 2015-06-13 19:41 UTC
