### ISSUE TITLE
Is this on melpa?

### ISSUE THREAD

**Issue by eflanigan00** [escherdragon/sunrise-commander#51] opened 2017-07-23 00:37 UTC
You should add it if it isn't.

**Comment by kensanata** [comment] 2017-09-07 09:24
The [homepage](http://joseito.republika.pl/sunrise-commander/) shows that there is a separate repo for Sunrise Commander.

**Comment by escherdragon** [comment] 2017-12-17 21:55
This is a duplicate of #29.

**Closed by escherdragon** 2017-12-17 21:55 UTC
